product 1 -> cart 1 -> user 1
product 2 -> cart 1 
product 1 -> cart 2 -> user 1
product 2 -> cart 2 


product 1 -> cart 3 -> user 2
product 2 -> cart 3
product 1 -> cart 4 -> user 2
product 2 -> cart 4 
